spring:
  datasource:
    druid:
      url: jdbc:mysql://192.168.5.141:3306/pochi?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8
      username: root
      password: yangdeshi
      driver-class-name: com.mysql.jdbc.Driver
      initialSize: 5
      minIdle: 5
      maxActive: 20
      maxWait: 10000
      testOnBorrow: true
      testOnReturn: false
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
#文件上传
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 20MB
  redis:
    host: 192.168.5.141
    port: 6379
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.demo.pochi
